#!/usr/bin/env node
// #625 — Open source license compatibility scanner + BOM gate.
//
// Inspects direct + transitive dependency licenses (package-lock.json,
// falling back to node_modules/*/package.json) against the approved
// compatibility matrix, regenerates THIRD_PARTY_LICENSES.md, and exits
// non-zero when a non-exceptioned DENIED (strong copyleft) license is
// introduced. REVIEW licenses warn; --strict turns them into failures.
//
// Usage:
//   node scripts/security/license_compliance.js [--bom <path>] [--strict] [--no-write]
//
// Zero runtime dependencies (node built-ins only).

import fs from "node:fs";
import path from "node:path";

const REPO_ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..", "..");
const args = process.argv.slice(2);
const getArg = (flag) => {
  const i = args.indexOf(flag);
  return i !== -1 ? args[i + 1] : undefined;
};
const BOM_PATH = path.resolve(REPO_ROOT, getArg("--bom") || "THIRD_PARTY_LICENSES.md");
const STRICT = args.includes("--strict");
const NO_WRITE = args.includes("--no-write");

import { EXCEPTIONS, classify } from "./license_policy.js";

function collectPackages() {
  const lockPath = path.join(REPO_ROOT, "package-lock.json");
  const lock = JSON.parse(fs.readFileSync(lockPath, "utf8"));
  const entries = [];
  for (const [p, meta] of Object.entries(lock.packages || {})) {
    if (!p) continue; // root entry
    let license = meta.license;
    if (!license) {
      // Fall back to installed package.json when the lock omits the field.
      try {
        const pkg = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, p, "package.json"), "utf8"));
        license = pkg.license || (Array.isArray(pkg.licenses) ? pkg.licenses.map((l) => l.type).join(" OR ") : undefined);
      } catch {
        license = undefined;
      }
    }
    entries.push({ name: p.replace(/^node_modules\//, ""), path: p, version: meta.version || "?", license: license || "UNKNOWN" });
  }
  return entries;
}

const pkgs = collectPackages();
let denied = [];
let review = [];
for (const pkg of pkgs) {
  pkg.status = classify(pkg.license);
  if (pkg.status === "denied" && EXCEPTIONS[pkg.path]) pkg.status = "excepted";
  if (pkg.status === "denied") denied.push(pkg);
  if (pkg.status === "review" || pkg.status === "excepted") review.push(pkg);
}

if (!NO_WRITE) {
  const rows = [...pkgs]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((p) => `| ${p.name} | ${p.version} | ${p.license} | ${p.status} |`);
  const deniedList = denied.length ? denied.map((p) => `- ${p.name}@${p.version} (${p.license})`).join("\n") : "None.";
  const body = `# Third-Party Licenses\n\n` +
    `> Auto-generated by \`scripts/security/license_compliance.js\` (#625). Do not edit by hand.\n` +
    `> Approved matrix: MIT, Apache-2.0, BSD-3-Clause, ISC (plus equivalent permissives).\n` +
    `> DENIED (strong copyleft GPL/AGPL) fails the build unless listed under Exceptions.\n\n` +
    `## Summary\n\n` +
    `- Total packages: ${pkgs.length}\n` +
    `- Approved: ${pkgs.filter((p) => p.status === "approved").length}\n` +
    `- Needs review: ${review.length}\n` +
    `- Denied (blocking): ${denied.length}\n\n` +
    `## Denied / blocking\n\n${deniedList}\n\n` +
    `## Exceptions (pre-existing, tracked)\n\n` +
    Object.entries(EXCEPTIONS).map(([k, v]) => `- \`${k}\`: ${v}`).join("\n") + `\n\n` +
    `## Bill of Materials\n\n| Package | Version | License | Status |\n| --- | --- | --- | --- |\n` +
    rows.join("\n") + `\n`;
  fs.writeFileSync(BOM_PATH, body);
  console.log(`license-compliance: BOM written (${pkgs.length} packages) -> ${path.relative(REPO_ROOT, BOM_PATH)}`);
}

for (const p of review.slice(0, 20)) console.log(`REVIEW: ${p.name}@${p.version} license=${p.license} status=${p.status}`);
if (review.length > 20) console.log(`... and ${review.length - 20} more (see BOM)`);
for (const p of denied) console.error(`DENIED: ${p.name}@${p.version} license=${p.license}`);

if (STRICT && review.filter((p) => p.status === "review").length > 0) {
  console.error("license-compliance: FAIL (--strict: review licenses present)");
  process.exit(1);
}
if (denied.length > 0) {
  console.error(`license-compliance: FAIL (${denied.length} denied license(s) not in EXCEPTIONS)`);
  process.exit(1);
}
console.log("license-compliance: OK");
