#!/usr/bin/env node
// #627 — Git commit sign-off & AI-attribution verification.
//
// Two modes:
//   Hook mode: node scripts/security/verify_commit_signatures.js <msg-file>
//     Runs from .husky/commit-msg. Requires a `Signed-off-by:` DCO trailer,
//     validates `Co-authored-by:` trailer format when present, and requires
//     an AI-attribution trailer when the message itself declares AI help.
//   Range mode: node scripts/security/verify_commit_signatures.js [--strict]
//               [--range <rev-range>]
//     Audits each commit's GPG/SSH signature status (`git log %G?`) plus
//     DCO sign-off. Locally unsigned commits warn; `--strict` (CI boundary)
//     rejects unsigned/unverified commits and missing sign-offs.
//
// Zero runtime dependencies (node built-ins only).

import fs from "node:fs";
import { execFileSync } from "node:child_process";

const argv = process.argv.slice(2);
const STRICT = argv.includes("--strict");
const rangeFlag = argv.indexOf("--range");
const RANGE = rangeFlag !== -1 ? argv[rangeFlag + 1] : "HEAD";
const msgFile = argv.find((a) => !a.startsWith("-") && a !== RANGE);

const SIGNOFF_RE = /^Signed-off-by:\s*.+\s<[^<>\s]+@[^<>\s]+>\s*$/im;
const COAUTHOR_RE = /^Co-authored-by:\s*.+\s<[^<>\s]+@[^<>\s]+>\s*$/im;
// Self-declared AI assistance without an attribution trailer.
const AI_HINT_RE = /\b(ai assistant|ai-assisted|claude|chatgpt|copilot|generated by ai|with ai help)\b/i;
// Good-signature statuses from `git log --format=%G?`.
const GOOD_SIG = new Set(["G"]);

function checkMessage(msg, { strict }) {
  const errors = [];
  const warnings = [];
  if (!SIGNOFF_RE.test(msg)) {
    errors.push("missing `Signed-off-by: Name <email>` DCO trailer (git commit -s)");
  }
  const coauthors = msg.split("\n").filter((l) => /^co-authored-by:/i.test(l));
  for (const line of coauthors) {
    if (!COAUTHOR_RE.test(line)) errors.push(`malformed Co-authored-by trailer: ${line}`);
  }
  if (AI_HINT_RE.test(msg) && !/co-authored-by:.*\b(ai|claude|chatgpt|copilot|bot)\b/i.test(msg)) {
    const m = "message declares AI assistance but has no `Co-authored-by: <AI> <email>` attribution trailer";
    (strict ? errors : warnings).push(m);
  }
  return { errors, warnings };
}

function gitLog(range) {
  // %H hash, %G? signature status (G/B/U/X/Y/R/E/N), %B raw body.
  const out = execFileSync("git", ["log", "--format=%H%x00%G?%x00%B%x1e", range], { encoding: "utf8" });
  return out.split("\x1e").map((s) => s.trim()).filter(Boolean).map((rec) => {
    const [hash, sig, ...bodyParts] = rec.split("\x00");
    return { hash, sig: (sig || "N").trim(), body: bodyParts.join("\x00") };
  });
}

// --- Hook mode -----------------------------------------------------------
if (msgFile && fs.existsSync(msgFile) && fs.statSync(msgFile).isFile()) {
  const msg = fs.readFileSync(msgFile, "utf8");
  const { errors, warnings } = checkMessage(msg, { strict: false });
  for (const w of warnings) console.warn(`commit-msg WARN: ${w}`);
  if (errors.length > 0) {
    for (const e of errors) console.error(`commit-msg ERROR: ${e}`);
    process.exit(1);
  }
  console.log("commit-msg: OK (DCO sign-off present)");
  process.exit(0);
}

// --- Range mode ----------------------------------------------------------
let commits;
try {
  commits = gitLog(RANGE);
} catch (e) {
  console.error(`verify-commit-signatures: cannot resolve range ${RANGE}: ${e.message}`);
  process.exit(2);
}
if (commits.length === 0) {
  console.log("verify-commit-signatures: no commits in range, OK");
  process.exit(0);
}

let fail = 0;
for (const c of commits.slice(-20)) { // cap output on long ranges
  const short = c.hash.slice(0, 8);
  const { errors, warnings } = checkMessage(c.body, { strict: STRICT });
  for (const w of warnings) console.warn(`${short} WARN: ${w}`);
  for (const e of errors) {
    console.error(`${short} ERROR: ${e}`);
    fail = 1;
  }
  if (!GOOD_SIG.has(c.sig)) {
    const m = `signature status '${c.sig}' (no valid GPG/SSH signature)`;
    if (STRICT) {
      console.error(`${short} ERROR: ${m}`);
      fail = 1;
    } else {
      console.warn(`${short} WARN: ${m} — sign with 'git commit -S' / configure gpg.ssh`);
    }
  }
}
if (commits.length > 20) console.log(`... audited ${commits.length} commits (showing last 20)`);
console.log(fail === 0 ? "verify-commit-signatures: OK" : "verify-commit-signatures: FAIL");
process.exit(fail);
